### ISSUE TITLE
Large memory usage and EOM for large DB

### ISSUE THREAD

**Issue by gnewton** [chrislusf/cdb64#2]
When I compile and run the below code, the resident size of the application grows very large, >=19GB, and then (on my 16GB laptop with 8GB swap) gets killed by the OS (Linux) due to OOM. It seems that databases larger than RAM might not be possible. 

```
package main

import (
	"fmt"
	"github.com/chrislusf/cdb64"
	"log"
	"strconv"
)

func main() {
	writer, err := cdb64.Create("./example.cdb")
	if err != nil {
		log.Fatal(err)
	}

	// Write some key/value pairs to the database.
	var n uint64 = 10000000000
	var i uint64

	for i = 0; i < n; i++ {
		writer.Put([]byte("Alice"+strconv.FormatUint(i, 10)), []byte("Practice"))
		writer.Put([]byte("Bob"+strconv.FormatUint(i, 10)), []byte("Hope"))
		writer.Put([]byte("Charlie"+strconv.FormatUint(i, 10)), []byte("Horse"))
		if i%10000 == 0 {
			fmt.Print(".")
		}
		if i%1000000 == 0 {
			fmt.Println(i)
		}
	}

	err = writer.Close()

	if err != nil {
		log.Fatal(err)
	}

}

```

**Comment by chrislusf** [comment]
The memory usage is determined by the size of the keys.

**Comment by gnewton** [comment]
I wonder if Writer.entries might be represented (optionally) ephemerally on-disk with something like boltdb, so that it would not have to be stored in memory. This would reduce write performance but would mean that very large databases could be generated that are much larger than available RAM. It could be optional, with the default being what is here now. It could be a configurable option to use the on-disk store for Writer.entries.
